# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/sm7250_common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/sm7250_common

PRODUCT_COPY_FILES += \
    vendor/motorola/sm7250_common/proprietary/bin/qspmsvc:$(TARGET_COPY_OUT_SYSTEM)/bin/qspmsvc \
    vendor/motorola/sm7250_common/proprietary/bin/vpsservice:$(TARGET_COPY_OUT_SYSTEM)/bin/vpsservice \
    vendor/motorola/sm7250_common/proprietary/etc/init/qspmsvc.rc:$(TARGET_COPY_OUT_SYSTEM)/etc/init/qspmsvc.rc \
    vendor/motorola/sm7250_common/proprietary/etc/sensors/proto/mot_barocal.proto:$(TARGET_COPY_OUT_SYSTEM)/etc/sensors/proto/mot_barocal.proto \
    vendor/motorola/sm7250_common/proprietary/etc/sensors/proto/mot_dsp_usound.proto:$(TARGET_COPY_OUT_SYSTEM)/etc/sensors/proto/mot_dsp_usound.proto \
    vendor/motorola/sm7250_common/proprietary/etc/sensors/proto/mot_movement.proto:$(TARGET_COPY_OUT_SYSTEM)/etc/sensors/proto/mot_movement.proto \
    vendor/motorola/sm7250_common/proprietary/etc/sensors/proto/mot_probe.proto:$(TARGET_COPY_OUT_SYSTEM)/etc/sensors/proto/mot_probe.proto \
    vendor/motorola/sm7250_common/proprietary/etc/sensors/proto/mot_vsync.proto:$(TARGET_COPY_OUT_SYSTEM)/etc/sensors/proto/mot_vsync.proto \
    vendor/motorola/sm7250_common/proprietary/etc/sensors/proto/sns_formatter.proto:$(TARGET_COPY_OUT_SYSTEM)/etc/sensors/proto/sns_formatter.proto \
    vendor/motorola/sm7250_common/proprietary/etc/sensors/proto/sns_panel_status.proto:$(TARGET_COPY_OUT_SYSTEM)/etc/sensors/proto/sns_panel_status.proto \
    vendor/motorola/sm7250_common/proprietary/etc/sensors/proto/tcs3708.proto:$(TARGET_COPY_OUT_SYSTEM)/etc/sensors/proto/tcs3708.proto \
    vendor/motorola/sm7250_common/proprietary/lib/com.motorola.hardware.biometric.fingerprint@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/com.motorola.hardware.biometric.fingerprint@1.0.so \
    vendor/motorola/sm7250_common/proprietary/lib/libbinauralrenderer_wrapper.qti.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libbinauralrenderer_wrapper.qti.so \
    vendor/motorola/sm7250_common/proprietary/lib/libhoaeffects.qti.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libhoaeffects.qti.so \
    vendor/motorola/sm7250_common/proprietary/lib/libhoaeffects_csim.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libhoaeffects_csim.so \
    vendor/motorola/sm7250_common/proprietary/lib/libskewknob_system.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libskewknob_system.so \
    vendor/motorola/sm7250_common/proprietary/lib/libvpsclient.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libvpsclient.so \
    vendor/motorola/sm7250_common/proprietary/lib/libvpsextension.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libvpsextension.so \
    vendor/motorola/sm7250_common/proprietary/lib64/com.motorola.hardware.biometric.fingerprint@1.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/com.motorola.hardware.biometric.fingerprint@1.0.so \
    vendor/motorola/sm7250_common/proprietary/lib64/libQOC.qti.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libQOC.qti.so \
    vendor/motorola/sm7250_common/proprietary/lib64/libbinauralrenderer_wrapper.qti.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libbinauralrenderer_wrapper.qti.so \
    vendor/motorola/sm7250_common/proprietary/lib64/libhoaeffects.qti.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libhoaeffects.qti.so \
    vendor/motorola/sm7250_common/proprietary/lib64/libhoaeffects_csim.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libhoaeffects_csim.so \
    vendor/motorola/sm7250_common/proprietary/lib64/libskewknob_system.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libskewknob_system.so \
    vendor/motorola/sm7250_common/proprietary/lib64/libvpsclient.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libvpsclient.so \
    vendor/motorola/sm7250_common/proprietary/lib64/libvpsextension.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libvpsextension.so \
    vendor/motorola/sm7250_common/proprietary/product/etc/dpm/dpm.conf:$(TARGET_COPY_OUT_PRODUCT)/etc/dpm/dpm.conf \
    vendor/motorola/sm7250_common/proprietary/product/etc/init/dpmd.rc:$(TARGET_COPY_OUT_PRODUCT)/etc/init/dpmd.rc \
    vendor/motorola/sm7250_common/proprietary/product/etc/ixitdata.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/ixitdata.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/nfcee_access.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/nfcee_access.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/android.hardware.nfc.hce.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/android.hardware.nfc.hce.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/android.hardware.nfc.hcef.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/android.hardware.nfc.hcef.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/android.hardware.nfc.uicc.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/android.hardware.nfc.uicc.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/android.hardware.nfc.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/android.hardware.nfc.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/com.motorola.androidx.camera.extensions.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.androidx.camera.extensions.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/com.motorola.camera2.content.ai.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.camera2.content.ai.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/com.motorola.camera2.whitney.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.camera2.whitney.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/com.motorola.imager.foles.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.imager.foles.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/com.motorola.motofpstouch.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.motofpstouch.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/com.motorola.motowaves.features.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.motowaves.features.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/com.motorola.photoeditor.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.photoeditor.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/com.nxp.mifare.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.nxp.mifare.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/com.qti.dpmframework.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.qti.dpmframework.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/com.st.android.nfc_extensions.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.st.android.nfc_extensions.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/dpmapi.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/dpmapi.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/privapp-permissions-com.motorola.dynamicvolume.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-com.motorola.dynamicvolume.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/privapp-permissions-com.motorola.gesture.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-com.motorola.gesture.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/permissions/privapp-permissions-com.motorola.imagertuning_foles.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-com.motorola.imagertuning_foles.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/sysconfig/hiddenapi-whitelist-com.motorola.dynamicvolume.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/hiddenapi-whitelist-com.motorola.dynamicvolume.xml \
    vendor/motorola/sm7250_common/proprietary/product/etc/sysconfig/hiddenapi-whitelist-com.motorola.motowaves.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/sysconfig/hiddenapi-whitelist-com.motorola.motowaves.xml \
    vendor/motorola/sm7250_common/proprietary/product/framework/com.android.ims.rcsmanager.jar:$(TARGET_COPY_OUT_PRODUCT)/framework/com.android.ims.rcsmanager.jar \
    vendor/motorola/sm7250_common/proprietary/product/framework/dpmapi.jar:$(TARGET_COPY_OUT_PRODUCT)/framework/dpmapi.jar \
    vendor/motorola/sm7250_common/proprietary/product/framework/uimgbalibrary.jar:$(TARGET_COPY_OUT_PRODUCT)/framework/uimgbalibrary.jar \
    vendor/motorola/sm7250_common/proprietary/product/framework/uimgbamanagerlibrary.jar:$(TARGET_COPY_OUT_PRODUCT)/framework/uimgbamanagerlibrary.jar \
    vendor/motorola/sm7250_common/proprietary/product/framework/vendor.qti.hardware.bluetooth_dun-V1.0-java.jar:$(TARGET_COPY_OUT_PRODUCT)/framework/vendor.qti.hardware.bluetooth_dun-V1.0-java.jar \
    vendor/motorola/sm7250_common/proprietary/product/framework/vendor.qti.hardware.slmadapter-V1.0-java.jar:$(TARGET_COPY_OUT_PRODUCT)/framework/vendor.qti.hardware.slmadapter-V1.0-java.jar \
    vendor/motorola/sm7250_common/proprietary/product/framework/vendor.qti.hardware.wigig.netperftuner-V1.0-java.jar:$(TARGET_COPY_OUT_PRODUCT)/framework/vendor.qti.hardware.wigig.netperftuner-V1.0-java.jar \
    vendor/motorola/sm7250_common/proprietary/product/framework/vendor.qti.hardware.wigig.supptunnel-V1.0-java.jar:$(TARGET_COPY_OUT_PRODUCT)/framework/vendor.qti.hardware.wigig.supptunnel-V1.0-java.jar \
    vendor/motorola/sm7250_common/proprietary/product/framework/vendor.qti.ims.rcsconfig-V1.1-java.jar:$(TARGET_COPY_OUT_PRODUCT)/framework/vendor.qti.ims.rcsconfig-V1.1-java.jar \
    vendor/motorola/sm7250_common/proprietary/product/lib/com.qualcomm.qti.dpm.api@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libarcsoft_aec_luma_calc_bm.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libarcsoft_aec_luma_calc_bm.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libarcsoft_aec_luma_calculation.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libarcsoft_aec_luma_calculation.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libdpmctmgr.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libdpmctmgr.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libdpmfdmgr.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libdpmfdmgr.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libdpmframework.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libdpmframework.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libdpmtcm.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libdpmtcm.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libdtaNfaProvider.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libdtaNfaProvider.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/liblayerext.qti.so:$(TARGET_COPY_OUT_PRODUCT)/lib/liblayerext.qti.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libmcf_native_window_helper.motocamera.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libmcf_native_window_helper.motocamera.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libmotocare.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libmotocare.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libnfc_st_dta.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libnfc_st_dta.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libnfc_st_dta_jni.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libnfc_st_dta_jni.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libsecureui_svcsock_system.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libsecureui_svcsock_system.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libslmiptablemgr.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libslmiptablemgr.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libsmomo.qti.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libsmomo.qti.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libstfactory.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libstfactory.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libstnfc-nci.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libstnfc-nci.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libstnfc_nci_jni.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libstnfc_nci_jni.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libtrigger-handler.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libtrigger-handler.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/libupdateprof.qti.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libupdateprof.qti.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.display.config@1.10.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.display.config@1.10.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.display.config@1.11.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.display.config@1.11.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.display.config@1.12.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.display.config@1.12.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.display.config@1.6.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.display.config@1.6.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.display.config@1.7.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.display.config@1.7.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.display.config@1.8.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.display.config@1.8.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.display.config@1.9.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.display.config@1.9.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.qti.data.factory@2.1.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.data.factory@2.1.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.qti.data.slm@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.data.slm@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.qti.hardware.factory@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.hardware.factory@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.qti.hardware.factory@1.1.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.hardware.factory@1.1.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.qti.hardware.qdutils_disp@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.hardware.qdutils_disp@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.qti.hardware.radio.qtiradio@2.4.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.hardware.radio.qtiradio@2.4.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.qti.hardware.radio.uim_remote_client@1.2.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.hardware.radio.uim_remote_client@1.2.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.qti.hardware.seccam@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.hardware.seccam@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.qti.hardware.slmadapter@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.hardware.slmadapter@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.qti.hardware.tui_comm@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.hardware.tui_comm@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.qti.hardware.wigig.netperftuner@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.hardware.wigig.netperftuner@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.qti.hardware.wigig.supptunnel@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.hardware.wigig.supptunnel@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.qti.ims.rcsconfig@1.1.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.ims.rcsconfig@1.1.so \
    vendor/motorola/sm7250_common/proprietary/product/lib/vendor.qti.qspmhal@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.qspmhal@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/com.qualcomm.qti.dpm.api@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/com.qualcomm.qti.dpm.api@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libBitmapOffsetCalculate_jni.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libBitmapOffsetCalculate_jni.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libdmengine.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libdmengine.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libdmjavaplugin.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libdmjavaplugin.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libdpmctmgr.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libdpmctmgr.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libdpmfdmgr.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libdpmfdmgr.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libdpmframework.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libdpmframework.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libdpmtcm.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libdpmtcm.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libdtaNfaProvider.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libdtaNfaProvider.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/liblayerext.qti.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/liblayerext.qti.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libmcf_native_window_helper.motocamera.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libmcf_native_window_helper.motocamera.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libmotocare.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libmotocare.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libnfc_st_dta.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libnfc_st_dta.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libnfc_st_dta_jni.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libnfc_st_dta_jni.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libslmiptablemgr.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libslmiptablemgr.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libsmomo.qti.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libsmomo.qti.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libstfactory.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libstfactory.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libstnfc-nci.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libstnfc-nci.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libstnfc_nci_jni.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libstnfc_nci_jni.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libtrigger-handler.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libtrigger-handler.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/libupdateprof.qti.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libupdateprof.qti.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.display.config@1.10.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.display.config@1.10.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.display.config@1.11.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.display.config@1.11.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.display.config@1.12.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.display.config@1.12.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.display.config@1.6.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.display.config@1.6.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.display.config@1.7.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.display.config@1.7.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.display.config@1.8.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.display.config@1.8.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.display.config@1.9.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.display.config@1.9.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.qti.data.factory@2.1.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.data.factory@2.1.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.qti.data.slm@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.data.slm@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.qti.hardware.factory@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.hardware.factory@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.qti.hardware.factory@1.1.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.hardware.factory@1.1.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.qti.hardware.qdutils_disp@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.hardware.qdutils_disp@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.qti.hardware.radio.qtiradio@2.4.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.hardware.radio.qtiradio@2.4.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.qti.hardware.radio.uim_remote_client@1.2.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.hardware.radio.uim_remote_client@1.2.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.qti.hardware.seccam@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.hardware.seccam@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.qti.hardware.slmadapter@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.hardware.slmadapter@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.qti.hardware.tui_comm@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.hardware.tui_comm@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.qti.hardware.wigig.netperftuner@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.hardware.wigig.netperftuner@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.qti.hardware.wigig.supptunnel@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.hardware.wigig.supptunnel@1.0.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.qti.ims.rcsconfig@1.1.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.ims.rcsconfig@1.1.so \
    vendor/motorola/sm7250_common/proprietary/product/lib64/vendor.qti.qspmhal@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.qspmhal@1.0.so

PRODUCT_PACKAGES += \
    VirtualUiccPayment_st \
    uimlpaservice \
    HotwordEnrollmentOKGoogleHEXAGON \
    HotwordEnrollmentXGoogleHEXAGON \
    WavesService \
    dpmserviceapp \
    com.motorola.androidx.camera.extensions \
    com.motorola.imager.foles \
    com.qti.dpmframework \
    com.st.android.nfc_extensions
