# Copyright (C) 2021 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/motorola/sm6150_common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/motorola/sm6150_common

PRODUCT_COPY_FILES += \
    vendor/motorola/sm6150_common/proprietary/bin/qvrservice:$(TARGET_COPY_OUT_SYSTEM)/bin/qvrservice \
    vendor/motorola/sm6150_common/proprietary/etc/sensors/proto/mot_drop.proto:$(TARGET_COPY_OUT_SYSTEM)/etc/sensors/proto/mot_drop.proto \
    vendor/motorola/sm6150_common/proprietary/etc/sensors/proto/mot_zshake.proto:$(TARGET_COPY_OUT_SYSTEM)/etc/sensors/proto/mot_zshake.proto \
    vendor/motorola/sm6150_common/proprietary/etc/sensors/proto/sns_formatter.proto:$(TARGET_COPY_OUT_SYSTEM)/etc/sensors/proto/sns_formatter.proto \
    vendor/motorola/sm6150_common/proprietary/etc/sensors/proto/sns_stm_pte.proto:$(TARGET_COPY_OUT_SYSTEM)/etc/sensors/proto/sns_stm_pte.proto \
    vendor/motorola/sm6150_common/proprietary/lib/libchromaflash.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libchromaflash.so \
    vendor/motorola/sm6150_common/proprietary/lib/libdualcameraddm.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libdualcameraddm.so \
    vendor/motorola/sm6150_common/proprietary/lib/libfiltergenerator.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libfiltergenerator.so \
    vendor/motorola/sm6150_common/proprietary/lib/libhazebuster.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libhazebuster.so \
    vendor/motorola/sm6150_common/proprietary/lib/libjni_blurbuster.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libjni_blurbuster.so \
    vendor/motorola/sm6150_common/proprietary/lib/libjni_chromaflash.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libjni_chromaflash.so \
    vendor/motorola/sm6150_common/proprietary/lib/libjni_dualcamera.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libjni_dualcamera.so \
    vendor/motorola/sm6150_common/proprietary/lib/libjni_filtergenerator.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libjni_filtergenerator.so \
    vendor/motorola/sm6150_common/proprietary/lib/libjni_hazebuster.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libjni_hazebuster.so \
    vendor/motorola/sm6150_common/proprietary/lib/libjni_optizoom.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libjni_optizoom.so \
    vendor/motorola/sm6150_common/proprietary/lib/libjni_seestraight.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libjni_seestraight.so \
    vendor/motorola/sm6150_common/proprietary/lib/libjni_sharpshooter.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libjni_sharpshooter.so \
    vendor/motorola/sm6150_common/proprietary/lib/libjni_stillmore.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libjni_stillmore.so \
    vendor/motorola/sm6150_common/proprietary/lib/libjni_trueportrait.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libjni_trueportrait.so \
    vendor/motorola/sm6150_common/proprietary/lib/libjni_truescanner_v2.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libjni_truescanner_v2.so \
    vendor/motorola/sm6150_common/proprietary/lib/libjni_ubifocus.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libjni_ubifocus.so \
    vendor/motorola/sm6150_common/proprietary/lib/liboptizoom.so:$(TARGET_COPY_OUT_SYSTEM)/lib/liboptizoom.so \
    vendor/motorola/sm6150_common/proprietary/lib/libqvr_cam_cdsp_driver_stub.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqvr_cam_cdsp_driver_stub.so \
    vendor/motorola/sm6150_common/proprietary/lib/libqvr_cdsp_driver_stub.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqvr_cdsp_driver_stub.so \
    vendor/motorola/sm6150_common/proprietary/lib/libqvr_eyetracking_plugin.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqvr_eyetracking_plugin.so \
    vendor/motorola/sm6150_common/proprietary/lib/libqvrcamera_client.qti.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqvrcamera_client.qti.so \
    vendor/motorola/sm6150_common/proprietary/lib/libqvrservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqvrservice.so \
    vendor/motorola/sm6150_common/proprietary/lib/libqvrservice_client.qti.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqvrservice_client.qti.so \
    vendor/motorola/sm6150_common/proprietary/lib/libqvrservice_ov7251_hvx_tuning.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqvrservice_ov7251_hvx_tuning.so \
    vendor/motorola/sm6150_common/proprietary/lib/libqvrservice_ov9282_hvx_tuning.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libqvrservice_ov9282_hvx_tuning.so \
    vendor/motorola/sm6150_common/proprietary/lib/libseemore.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libseemore.so \
    vendor/motorola/sm6150_common/proprietary/lib/libseestraight.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libseestraight.so \
    vendor/motorola/sm6150_common/proprietary/lib/libtrueportrait.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libtrueportrait.so \
    vendor/motorola/sm6150_common/proprietary/lib/libtruescanner.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libtruescanner.so \
    vendor/motorola/sm6150_common/proprietary/lib/libubifocus.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libubifocus.so \
    vendor/motorola/sm6150_common/proprietary/lib/libvndfwk_detect_jni.qti.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libvndfwk_detect_jni.qti.so \
    vendor/motorola/sm6150_common/proprietary/lib/rfsa/adsp/libqvr_dsp_driver_skel.so:$(TARGET_COPY_OUT_SYSTEM)/lib/rfsa/adsp/libqvr_dsp_driver_skel.so \
    vendor/motorola/sm6150_common/proprietary/lib/rfsa/adsp/libtracker_6dof_skel_8150.so:$(TARGET_COPY_OUT_SYSTEM)/lib/rfsa/adsp/libtracker_6dof_skel_8150.so \
    vendor/motorola/sm6150_common/proprietary/lib/vendor.goodix.hardware.biometrics.fingerprint@3.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib/vendor.goodix.hardware.biometrics.fingerprint@3.0.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libcameraservice.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libcameraservice.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libchromaflash.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libchromaflash.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libdualcameraddm.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libdualcameraddm.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libfiltergenerator.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libfiltergenerator.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libhazebuster.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libhazebuster.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libimgTuner_jni.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libimgTuner_jni.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libjni_blurbuster.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_blurbuster.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libjni_chromaflash.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_chromaflash.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libjni_clearsight.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_clearsight.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libjni_dualcamera.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_dualcamera.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libjni_filtergenerator.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_filtergenerator.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libjni_hazebuster.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_hazebuster.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libjni_optizoom.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_optizoom.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libjni_pacprocessor.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_pacprocessor.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libjni_seestraight.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_seestraight.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libjni_sharpshooter.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_sharpshooter.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libjni_stillmore.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_stillmore.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libjni_trueportrait.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_trueportrait.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libjni_truescanner_v2.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_truescanner_v2.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libjni_ubifocus.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libjni_ubifocus.so \
    vendor/motorola/sm6150_common/proprietary/lib64/liboptizoom.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/liboptizoom.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libqvrcamera_client.qti.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libqvrcamera_client.qti.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libqvrservice_client.qti.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libqvrservice_client.qti.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libseemore.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libseemore.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libseestraight.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libseestraight.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libtrueportrait.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libtrueportrait.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libtruescanner.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libtruescanner.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libubifocus.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libubifocus.so \
    vendor/motorola/sm6150_common/proprietary/lib64/libvndfwk_detect_jni.qti.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/libvndfwk_detect_jni.qti.so \
    vendor/motorola/sm6150_common/proprietary/lib64/vendor.goodix.hardware.biometrics.fingerprint@3.0.so:$(TARGET_COPY_OUT_SYSTEM)/lib64/vendor.goodix.hardware.biometrics.fingerprint@3.0.so \
    vendor/motorola/sm6150_common/proprietary/product/etc/permissions/com.motorola.androidx.camera.extensions.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.androidx.camera.extensions.xml \
    vendor/motorola/sm6150_common/proprietary/product/etc/permissions/com.motorola.camera2.content.ai.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.camera2.content.ai.xml \
    vendor/motorola/sm6150_common/proprietary/product/etc/permissions/com.motorola.camera2.whitney.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.camera2.whitney.xml \
    vendor/motorola/sm6150_common/proprietary/product/etc/permissions/com.motorola.imager.foles.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.imager.foles.xml \
    vendor/motorola/sm6150_common/proprietary/product/etc/permissions/com.motorola.omadm.service.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.omadm.service.xml \
    vendor/motorola/sm6150_common/proprietary/product/etc/permissions/com.motorola.photoeditor.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.photoeditor.xml \
    vendor/motorola/sm6150_common/proprietary/product/etc/permissions/com.motorola.software.fmradioservice.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/com.motorola.software.fmradioservice.xml \
    vendor/motorola/sm6150_common/proprietary/product/etc/permissions/privapp-permissions-com.motorola.imagertuning_foles.xml:$(TARGET_COPY_OUT_PRODUCT)/etc/permissions/privapp-permissions-com.motorola.imagertuning_foles.xml \
    vendor/motorola/sm6150_common/proprietary/product/framework/dpmapi.jar:$(TARGET_COPY_OUT_PRODUCT)/framework/dpmapi.jar \
    vendor/motorola/sm6150_common/proprietary/product/framework/vendor.qti.hardware.bluetooth_dun-V1.0-java.jar:$(TARGET_COPY_OUT_PRODUCT)/framework/vendor.qti.hardware.bluetooth_dun-V1.0-java.jar \
    vendor/motorola/sm6150_common/proprietary/product/lib/libmcf_native_window_helper.motocamera.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libmcf_native_window_helper.motocamera.so \
    vendor/motorola/sm6150_common/proprietary/product/lib/libmotocare.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libmotocare.so \
    vendor/motorola/sm6150_common/proprietary/product/lib/libqcomfm_jni_product.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libqcomfm_jni_product.so \
    vendor/motorola/sm6150_common/proprietary/product/lib/libseccam.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libseccam.so \
    vendor/motorola/sm6150_common/proprietary/product/lib/libsecureui_svcsock_system.so:$(TARGET_COPY_OUT_PRODUCT)/lib/libsecureui_svcsock_system.so \
    vendor/motorola/sm6150_common/proprietary/product/lib/vendor.qti.hardware.factory@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.hardware.factory@1.0.so \
    vendor/motorola/sm6150_common/proprietary/product/lib/vendor.qti.hardware.factory@1.1.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.hardware.factory@1.1.so \
    vendor/motorola/sm6150_common/proprietary/product/lib/vendor.qti.hardware.qseecom@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib/vendor.qti.hardware.qseecom@1.0.so \
    vendor/motorola/sm6150_common/proprietary/product/lib64/libGPQTEEC_system.qti.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libGPQTEEC_system.qti.so \
    vendor/motorola/sm6150_common/proprietary/product/lib64/libGPTEE_system.qti.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libGPTEE_system.qti.so \
    vendor/motorola/sm6150_common/proprietary/product/lib64/libQTEEConnector_system.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libQTEEConnector_system.so \
    vendor/motorola/sm6150_common/proprietary/product/lib64/libdmengine.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libdmengine.so \
    vendor/motorola/sm6150_common/proprietary/product/lib64/libdmjavaplugin.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libdmjavaplugin.so \
    vendor/motorola/sm6150_common/proprietary/product/lib64/libmotocare.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libmotocare.so \
    vendor/motorola/sm6150_common/proprietary/product/lib64/libqcomfm_jni_product.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libqcomfm_jni_product.so \
    vendor/motorola/sm6150_common/proprietary/product/lib64/libseccam.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libseccam.so \
    vendor/motorola/sm6150_common/proprietary/product/lib64/libsecureui_svcsock_system.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/libsecureui_svcsock_system.so \
    vendor/motorola/sm6150_common/proprietary/product/lib64/vendor.qti.hardware.factory@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.hardware.factory@1.0.so \
    vendor/motorola/sm6150_common/proprietary/product/lib64/vendor.qti.hardware.factory@1.1.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.hardware.factory@1.1.so \
    vendor/motorola/sm6150_common/proprietary/product/lib64/vendor.qti.hardware.qseecom@1.0.so:$(TARGET_COPY_OUT_PRODUCT)/lib64/vendor.qti.hardware.qseecom@1.0.so \
    vendor/motorola/sm6150_common/proprietary/usr/idc/uinput_nav.idc:$(TARGET_COPY_OUT_SYSTEM)/usr/idc/uinput_nav.idc \
    vendor/motorola/sm6150_common/proprietary/usr/keylayout/uinput_nav.kl:$(TARGET_COPY_OUT_SYSTEM)/usr/keylayout/uinput_nav.kl

PRODUCT_PACKAGES += \
    vendor.goodix.hardware.biometrics.fingerprint-V3.0-java \
    com.motorola.androidx.camera.extensions \
    com.motorola.imager.foles \
    com.qti.dpmframework
